version: "3"
services:
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ}
        - INSTALL_XDEBUG=${WORKSPACE_INSTALL_XDEBUG}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ${PROJECT_PATH}:/work
      - ./logs:/var/log
      #- ./logs:/work/myapp/storage/logs
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}

  web:
    # version確認（alpineの最新で良いはず）
    image: nginx:1.24.0-alpine
    depends_on:
      - app
    ports:
      - ${WEB_PORT}:443
      - ${WEB_PORT_HTTP}:80
    volumes:
      - ${PROJECT_PATH}:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${SSL_CRT_PATH}:/etc/nginx/certs/server.crt
      - ${SSL_KEY_PATH}:/etc/nginx/certs/server.key
      - ${SSL_PASS_PATH}:/etc/nginx/certs/server.password
    environment:
      - TZ=${TZ}

  db:
    # version確認
    image: mysql:8
    volumes:
      # fixme: project名によって変更
      - docker-laravel-env-db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
      - MYSQL_ROOT_HOST=%
    ports:
      - ${DB_PORT}:3306
    user: 1000:1000
  
volumes:
  # fixme: project名によって変更
  docker-laravel-env-db-store: